### ISSUE TITLE
Wants initial blank line when class declaration is broken over lines

### ISSUE THREAD

**Issue by pburkindine** [chinchiheather/tslint-lines-between-class-members#19]
```
export class ExtremelyOverlongClassNameCausingLineBreak
  implements BaseClass {
  constructor() {}
}
```

When prettier cleans up a class declaration to span multiple lines (or if you do so manually), the rule will decide here that constructor is missing a leading blank line (which, unfortunately, prettier will then remove)

**Comment by pburkindine** [comment]
@chinchiheather Is there any update on this?

**Comment by chinchiheather** [comment]
Hi @pburkindine , sorry I've been a bit MIA the last few months, I'll have a look into it, shouldn't be too difficult to fix I think

**Comment by chinchiheather** [comment]
I have implemented the fix and released 1.3.2

**Comment by pburkindine** [comment]
@chinchiheather Thanks, it's much improved!  However I'm still seeing the issue in one case:

```
export class VeryVeryVeryVeryLongClassName extends VeryVerVeryLongBaseClassName<
  SomeType
> {
  constructor() {
    super('foo);
  }
```
